// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_2eproto;
namespace game {
class BulletBatch;
struct BulletBatchDefaultTypeInternal;
extern BulletBatchDefaultTypeInternal _BulletBatch_default_instance_;
class ClientInput;
struct ClientInputDefaultTypeInternal;
extern ClientInputDefaultTypeInternal _ClientInput_default_instance_;
class EntityState;
struct EntityStateDefaultTypeInternal;
extern EntityStateDefaultTypeInternal _EntityState_default_instance_;
class ServerSnapshot;
struct ServerSnapshotDefaultTypeInternal;
extern ServerSnapshotDefaultTypeInternal _ServerSnapshot_default_instance_;
class SpawnBullet;
struct SpawnBulletDefaultTypeInternal;
extern SpawnBulletDefaultTypeInternal _SpawnBullet_default_instance_;
class Vec2;
struct Vec2DefaultTypeInternal;
extern Vec2DefaultTypeInternal _Vec2_default_instance_;
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> ::game::BulletBatch* Arena::CreateMaybeMessage<::game::BulletBatch>(Arena*);
template<> ::game::ClientInput* Arena::CreateMaybeMessage<::game::ClientInput>(Arena*);
template<> ::game::EntityState* Arena::CreateMaybeMessage<::game::EntityState>(Arena*);
template<> ::game::ServerSnapshot* Arena::CreateMaybeMessage<::game::ServerSnapshot>(Arena*);
template<> ::game::SpawnBullet* Arena::CreateMaybeMessage<::game::SpawnBullet>(Arena*);
template<> ::game::Vec2* Arena::CreateMaybeMessage<::game::Vec2>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace game {

enum EntityType : int {
  PLAYER = 0,
  ENEMY = 1,
  BULLET = 2,
  PLATFORM = 3,
  EntityType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EntityType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EntityType_IsValid(int value);
constexpr EntityType EntityType_MIN = PLAYER;
constexpr EntityType EntityType_MAX = PLATFORM;
constexpr int EntityType_ARRAYSIZE = EntityType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EntityType_descriptor();
template<typename T>
inline const std::string& EntityType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EntityType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EntityType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EntityType_descriptor(), enum_t_value);
}
inline bool EntityType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EntityType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EntityType>(
    EntityType_descriptor(), name, value);
}
// ===================================================================

class Vec2 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.Vec2) */ {
 public:
  inline Vec2() : Vec2(nullptr) {}
  ~Vec2() override;
  explicit PROTOBUF_CONSTEXPR Vec2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec2(const Vec2& from);
  Vec2(Vec2&& from) noexcept
    : Vec2() {
    *this = ::std::move(from);
  }

  inline Vec2& operator=(const Vec2& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec2& operator=(Vec2&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec2& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec2* internal_default_instance() {
    return reinterpret_cast<const Vec2*>(
               &_Vec2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vec2& a, Vec2& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec2* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vec2>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vec2& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Vec2& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vec2* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.Vec2";
  }
  protected:
  explicit Vec2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:game.Vec2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class ClientInput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.ClientInput) */ {
 public:
  inline ClientInput() : ClientInput(nullptr) {}
  ~ClientInput() override;
  explicit PROTOBUF_CONSTEXPR ClientInput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientInput(const ClientInput& from);
  ClientInput(ClientInput&& from) noexcept
    : ClientInput() {
    *this = ::std::move(from);
  }

  inline ClientInput& operator=(const ClientInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientInput& operator=(ClientInput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientInput& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientInput* internal_default_instance() {
    return reinterpret_cast<const ClientInput*>(
               &_ClientInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ClientInput& a, ClientInput& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientInput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientInput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientInput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientInput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientInput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientInput& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientInput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.ClientInput";
  }
  protected:
  explicit ClientInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 1,
    kInputBitsFieldNumber = 2,
  };
  // string token = 1;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // uint32 input_bits = 2;
  void clear_input_bits();
  uint32_t input_bits() const;
  void set_input_bits(uint32_t value);
  private:
  uint32_t _internal_input_bits() const;
  void _internal_set_input_bits(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.ClientInput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
  uint32_t input_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class EntityState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.EntityState) */ {
 public:
  inline EntityState() : EntityState(nullptr) {}
  ~EntityState() override;
  explicit PROTOBUF_CONSTEXPR EntityState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EntityState(const EntityState& from);
  EntityState(EntityState&& from) noexcept
    : EntityState() {
    *this = ::std::move(from);
  }

  inline EntityState& operator=(const EntityState& from) {
    CopyFrom(from);
    return *this;
  }
  inline EntityState& operator=(EntityState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EntityState& default_instance() {
    return *internal_default_instance();
  }
  static inline const EntityState* internal_default_instance() {
    return reinterpret_cast<const EntityState*>(
               &_EntityState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(EntityState& a, EntityState& b) {
    a.Swap(&b);
  }
  inline void Swap(EntityState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EntityState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EntityState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EntityState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EntityState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EntityState& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EntityState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.EntityState";
  }
  protected:
  explicit EntityState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 3,
    kVelFieldNumber = 4,
    kIdFieldNumber = 1,
    kTypeFieldNumber = 2,
    kHpFieldNumber = 5,
    kOwnerFieldNumber = 7,
    kAnimFieldNumber = 6,
    kStateFieldNumber = 8,
  };
  // .game.Vec2 pos = 3;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::game::Vec2& pos() const;
  PROTOBUF_NODISCARD ::game::Vec2* release_pos();
  ::game::Vec2* mutable_pos();
  void set_allocated_pos(::game::Vec2* pos);
  private:
  const ::game::Vec2& _internal_pos() const;
  ::game::Vec2* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::game::Vec2* pos);
  ::game::Vec2* unsafe_arena_release_pos();

  // .game.Vec2 vel = 4;
  bool has_vel() const;
  private:
  bool _internal_has_vel() const;
  public:
  void clear_vel();
  const ::game::Vec2& vel() const;
  PROTOBUF_NODISCARD ::game::Vec2* release_vel();
  ::game::Vec2* mutable_vel();
  void set_allocated_vel(::game::Vec2* vel);
  private:
  const ::game::Vec2& _internal_vel() const;
  ::game::Vec2* _internal_mutable_vel();
  public:
  void unsafe_arena_set_allocated_vel(
      ::game::Vec2* vel);
  ::game::Vec2* unsafe_arena_release_vel();

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // .game.EntityType type = 2;
  void clear_type();
  ::game::EntityType type() const;
  void set_type(::game::EntityType value);
  private:
  ::game::EntityType _internal_type() const;
  void _internal_set_type(::game::EntityType value);
  public:

  // int32 hp = 5;
  void clear_hp();
  int32_t hp() const;
  void set_hp(int32_t value);
  private:
  int32_t _internal_hp() const;
  void _internal_set_hp(int32_t value);
  public:

  // uint64 owner = 7;
  void clear_owner();
  uint64_t owner() const;
  void set_owner(uint64_t value);
  private:
  uint64_t _internal_owner() const;
  void _internal_set_owner(uint64_t value);
  public:

  // uint32 anim = 6;
  void clear_anim();
  uint32_t anim() const;
  void set_anim(uint32_t value);
  private:
  uint32_t _internal_anim() const;
  void _internal_set_anim(uint32_t value);
  public:

  // uint32 state = 8;
  void clear_state();
  uint32_t state() const;
  void set_state(uint32_t value);
  private:
  uint32_t _internal_state() const;
  void _internal_set_state(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.EntityState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::game::Vec2* pos_;
  ::game::Vec2* vel_;
  uint64_t id_;
  int type_;
  int32_t hp_;
  uint64_t owner_;
  uint32_t anim_;
  uint32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class ServerSnapshot final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.ServerSnapshot) */ {
 public:
  inline ServerSnapshot() : ServerSnapshot(nullptr) {}
  ~ServerSnapshot() override;
  explicit PROTOBUF_CONSTEXPR ServerSnapshot(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerSnapshot(const ServerSnapshot& from);
  ServerSnapshot(ServerSnapshot&& from) noexcept
    : ServerSnapshot() {
    *this = ::std::move(from);
  }

  inline ServerSnapshot& operator=(const ServerSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerSnapshot& operator=(ServerSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerSnapshot& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerSnapshot* internal_default_instance() {
    return reinterpret_cast<const ServerSnapshot*>(
               &_ServerSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ServerSnapshot& a, ServerSnapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerSnapshot* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerSnapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerSnapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerSnapshot>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerSnapshot& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ServerSnapshot& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerSnapshot* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.ServerSnapshot";
  }
  protected:
  explicit ServerSnapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntitiesFieldNumber = 3,
    kRemovedIdsFieldNumber = 4,
    kServerTickFieldNumber = 1,
    kSnapshotSeqFieldNumber = 2,
  };
  // repeated .game.EntityState entities = 3;
  int entities_size() const;
  private:
  int _internal_entities_size() const;
  public:
  void clear_entities();
  ::game::EntityState* mutable_entities(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::EntityState >*
      mutable_entities();
  private:
  const ::game::EntityState& _internal_entities(int index) const;
  ::game::EntityState* _internal_add_entities();
  public:
  const ::game::EntityState& entities(int index) const;
  ::game::EntityState* add_entities();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::EntityState >&
      entities() const;

  // repeated uint64 removed_ids = 4;
  int removed_ids_size() const;
  private:
  int _internal_removed_ids_size() const;
  public:
  void clear_removed_ids();
  private:
  uint64_t _internal_removed_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_removed_ids() const;
  void _internal_add_removed_ids(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_removed_ids();
  public:
  uint64_t removed_ids(int index) const;
  void set_removed_ids(int index, uint64_t value);
  void add_removed_ids(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      removed_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_removed_ids();

  // uint32 server_tick = 1;
  void clear_server_tick();
  uint32_t server_tick() const;
  void set_server_tick(uint32_t value);
  private:
  uint32_t _internal_server_tick() const;
  void _internal_set_server_tick(uint32_t value);
  public:

  // uint32 snapshot_seq = 2;
  void clear_snapshot_seq();
  uint32_t snapshot_seq() const;
  void set_snapshot_seq(uint32_t value);
  private:
  uint32_t _internal_snapshot_seq() const;
  void _internal_set_snapshot_seq(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.ServerSnapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::EntityState > entities_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > removed_ids_;
  mutable std::atomic<int> _removed_ids_cached_byte_size_;
  uint32_t server_tick_;
  uint32_t snapshot_seq_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class SpawnBullet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.SpawnBullet) */ {
 public:
  inline SpawnBullet() : SpawnBullet(nullptr) {}
  ~SpawnBullet() override;
  explicit PROTOBUF_CONSTEXPR SpawnBullet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpawnBullet(const SpawnBullet& from);
  SpawnBullet(SpawnBullet&& from) noexcept
    : SpawnBullet() {
    *this = ::std::move(from);
  }

  inline SpawnBullet& operator=(const SpawnBullet& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpawnBullet& operator=(SpawnBullet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpawnBullet& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpawnBullet* internal_default_instance() {
    return reinterpret_cast<const SpawnBullet*>(
               &_SpawnBullet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SpawnBullet& a, SpawnBullet& b) {
    a.Swap(&b);
  }
  inline void Swap(SpawnBullet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpawnBullet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpawnBullet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpawnBullet>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpawnBullet& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SpawnBullet& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpawnBullet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.SpawnBullet";
  }
  protected:
  explicit SpawnBullet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 3,
    kVelFieldNumber = 4,
    kIdFieldNumber = 1,
    kOwnerFieldNumber = 2,
    kDamageFieldNumber = 5,
    kTtlMsFieldNumber = 6,
  };
  // .game.Vec2 pos = 3;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::game::Vec2& pos() const;
  PROTOBUF_NODISCARD ::game::Vec2* release_pos();
  ::game::Vec2* mutable_pos();
  void set_allocated_pos(::game::Vec2* pos);
  private:
  const ::game::Vec2& _internal_pos() const;
  ::game::Vec2* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::game::Vec2* pos);
  ::game::Vec2* unsafe_arena_release_pos();

  // .game.Vec2 vel = 4;
  bool has_vel() const;
  private:
  bool _internal_has_vel() const;
  public:
  void clear_vel();
  const ::game::Vec2& vel() const;
  PROTOBUF_NODISCARD ::game::Vec2* release_vel();
  ::game::Vec2* mutable_vel();
  void set_allocated_vel(::game::Vec2* vel);
  private:
  const ::game::Vec2& _internal_vel() const;
  ::game::Vec2* _internal_mutable_vel();
  public:
  void unsafe_arena_set_allocated_vel(
      ::game::Vec2* vel);
  ::game::Vec2* unsafe_arena_release_vel();

  // uint32 id = 1;
  void clear_id();
  uint32_t id() const;
  void set_id(uint32_t value);
  private:
  uint32_t _internal_id() const;
  void _internal_set_id(uint32_t value);
  public:

  // uint32 owner = 2;
  void clear_owner();
  uint32_t owner() const;
  void set_owner(uint32_t value);
  private:
  uint32_t _internal_owner() const;
  void _internal_set_owner(uint32_t value);
  public:

  // uint32 damage = 5;
  void clear_damage();
  uint32_t damage() const;
  void set_damage(uint32_t value);
  private:
  uint32_t _internal_damage() const;
  void _internal_set_damage(uint32_t value);
  public:

  // uint32 ttl_ms = 6;
  void clear_ttl_ms();
  uint32_t ttl_ms() const;
  void set_ttl_ms(uint32_t value);
  private:
  uint32_t _internal_ttl_ms() const;
  void _internal_set_ttl_ms(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.SpawnBullet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::game::Vec2* pos_;
  ::game::Vec2* vel_;
  uint32_t id_;
  uint32_t owner_;
  uint32_t damage_;
  uint32_t ttl_ms_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class BulletBatch final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.BulletBatch) */ {
 public:
  inline BulletBatch() : BulletBatch(nullptr) {}
  ~BulletBatch() override;
  explicit PROTOBUF_CONSTEXPR BulletBatch(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BulletBatch(const BulletBatch& from);
  BulletBatch(BulletBatch&& from) noexcept
    : BulletBatch() {
    *this = ::std::move(from);
  }

  inline BulletBatch& operator=(const BulletBatch& from) {
    CopyFrom(from);
    return *this;
  }
  inline BulletBatch& operator=(BulletBatch&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BulletBatch& default_instance() {
    return *internal_default_instance();
  }
  static inline const BulletBatch* internal_default_instance() {
    return reinterpret_cast<const BulletBatch*>(
               &_BulletBatch_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(BulletBatch& a, BulletBatch& b) {
    a.Swap(&b);
  }
  inline void Swap(BulletBatch* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BulletBatch* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BulletBatch* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BulletBatch>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BulletBatch& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BulletBatch& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BulletBatch* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.BulletBatch";
  }
  protected:
  explicit BulletBatch(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpawnsFieldNumber = 1,
    kDestroyedIdsFieldNumber = 2,
    kServerTickFieldNumber = 3,
  };
  // repeated .game.SpawnBullet spawns = 1;
  int spawns_size() const;
  private:
  int _internal_spawns_size() const;
  public:
  void clear_spawns();
  ::game::SpawnBullet* mutable_spawns(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::SpawnBullet >*
      mutable_spawns();
  private:
  const ::game::SpawnBullet& _internal_spawns(int index) const;
  ::game::SpawnBullet* _internal_add_spawns();
  public:
  const ::game::SpawnBullet& spawns(int index) const;
  ::game::SpawnBullet* add_spawns();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::SpawnBullet >&
      spawns() const;

  // repeated uint32 destroyed_ids = 2;
  int destroyed_ids_size() const;
  private:
  int _internal_destroyed_ids_size() const;
  public:
  void clear_destroyed_ids();
  private:
  uint32_t _internal_destroyed_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_destroyed_ids() const;
  void _internal_add_destroyed_ids(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_destroyed_ids();
  public:
  uint32_t destroyed_ids(int index) const;
  void set_destroyed_ids(int index, uint32_t value);
  void add_destroyed_ids(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      destroyed_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_destroyed_ids();

  // uint32 server_tick = 3;
  void clear_server_tick();
  uint32_t server_tick() const;
  void set_server_tick(uint32_t value);
  private:
  uint32_t _internal_server_tick() const;
  void _internal_set_server_tick(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.BulletBatch)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::SpawnBullet > spawns_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > destroyed_ids_;
  mutable std::atomic<int> _destroyed_ids_cached_byte_size_;
  uint32_t server_tick_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vec2

// float x = 1;
inline void Vec2::clear_x() {
  x_ = 0;
}
inline float Vec2::_internal_x() const {
  return x_;
}
inline float Vec2::x() const {
  // @@protoc_insertion_point(field_get:game.Vec2.x)
  return _internal_x();
}
inline void Vec2::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vec2::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:game.Vec2.x)
}

// float y = 2;
inline void Vec2::clear_y() {
  y_ = 0;
}
inline float Vec2::_internal_y() const {
  return y_;
}
inline float Vec2::y() const {
  // @@protoc_insertion_point(field_get:game.Vec2.y)
  return _internal_y();
}
inline void Vec2::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vec2::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:game.Vec2.y)
}

// -------------------------------------------------------------------

// ClientInput

// string token = 1;
inline void ClientInput::clear_token() {
  token_.ClearToEmpty();
}
inline const std::string& ClientInput::token() const {
  // @@protoc_insertion_point(field_get:game.ClientInput.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientInput::set_token(ArgT0&& arg0, ArgT... args) {
 
 token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.ClientInput.token)
}
inline std::string* ClientInput::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:game.ClientInput.token)
  return _s;
}
inline const std::string& ClientInput::_internal_token() const {
  return token_.Get();
}
inline void ClientInput::_internal_set_token(const std::string& value) {
  
  token_.Set(value, GetArenaForAllocation());
}
inline std::string* ClientInput::_internal_mutable_token() {
  
  return token_.Mutable(GetArenaForAllocation());
}
inline std::string* ClientInput::release_token() {
  // @@protoc_insertion_point(field_release:game.ClientInput.token)
  return token_.Release();
}
inline void ClientInput::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (token_.IsDefault()) {
    token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.ClientInput.token)
}

// uint32 input_bits = 2;
inline void ClientInput::clear_input_bits() {
  input_bits_ = 0u;
}
inline uint32_t ClientInput::_internal_input_bits() const {
  return input_bits_;
}
inline uint32_t ClientInput::input_bits() const {
  // @@protoc_insertion_point(field_get:game.ClientInput.input_bits)
  return _internal_input_bits();
}
inline void ClientInput::_internal_set_input_bits(uint32_t value) {
  
  input_bits_ = value;
}
inline void ClientInput::set_input_bits(uint32_t value) {
  _internal_set_input_bits(value);
  // @@protoc_insertion_point(field_set:game.ClientInput.input_bits)
}

// -------------------------------------------------------------------

// EntityState

// uint64 id = 1;
inline void EntityState::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t EntityState::_internal_id() const {
  return id_;
}
inline uint64_t EntityState::id() const {
  // @@protoc_insertion_point(field_get:game.EntityState.id)
  return _internal_id();
}
inline void EntityState::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void EntityState::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:game.EntityState.id)
}

// .game.EntityType type = 2;
inline void EntityState::clear_type() {
  type_ = 0;
}
inline ::game::EntityType EntityState::_internal_type() const {
  return static_cast< ::game::EntityType >(type_);
}
inline ::game::EntityType EntityState::type() const {
  // @@protoc_insertion_point(field_get:game.EntityState.type)
  return _internal_type();
}
inline void EntityState::_internal_set_type(::game::EntityType value) {
  
  type_ = value;
}
inline void EntityState::set_type(::game::EntityType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:game.EntityState.type)
}

// .game.Vec2 pos = 3;
inline bool EntityState::_internal_has_pos() const {
  return this != internal_default_instance() && pos_ != nullptr;
}
inline bool EntityState::has_pos() const {
  return _internal_has_pos();
}
inline void EntityState::clear_pos() {
  if (GetArenaForAllocation() == nullptr && pos_ != nullptr) {
    delete pos_;
  }
  pos_ = nullptr;
}
inline const ::game::Vec2& EntityState::_internal_pos() const {
  const ::game::Vec2* p = pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::game::Vec2&>(
      ::game::_Vec2_default_instance_);
}
inline const ::game::Vec2& EntityState::pos() const {
  // @@protoc_insertion_point(field_get:game.EntityState.pos)
  return _internal_pos();
}
inline void EntityState::unsafe_arena_set_allocated_pos(
    ::game::Vec2* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pos_);
  }
  pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game.EntityState.pos)
}
inline ::game::Vec2* EntityState::release_pos() {
  
  ::game::Vec2* temp = pos_;
  pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game::Vec2* EntityState::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:game.EntityState.pos)
  
  ::game::Vec2* temp = pos_;
  pos_ = nullptr;
  return temp;
}
inline ::game::Vec2* EntityState::_internal_mutable_pos() {
  
  if (pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::game::Vec2>(GetArenaForAllocation());
    pos_ = p;
  }
  return pos_;
}
inline ::game::Vec2* EntityState::mutable_pos() {
  ::game::Vec2* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:game.EntityState.pos)
  return _msg;
}
inline void EntityState::set_allocated_pos(::game::Vec2* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete pos_;
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos);
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:game.EntityState.pos)
}

// .game.Vec2 vel = 4;
inline bool EntityState::_internal_has_vel() const {
  return this != internal_default_instance() && vel_ != nullptr;
}
inline bool EntityState::has_vel() const {
  return _internal_has_vel();
}
inline void EntityState::clear_vel() {
  if (GetArenaForAllocation() == nullptr && vel_ != nullptr) {
    delete vel_;
  }
  vel_ = nullptr;
}
inline const ::game::Vec2& EntityState::_internal_vel() const {
  const ::game::Vec2* p = vel_;
  return p != nullptr ? *p : reinterpret_cast<const ::game::Vec2&>(
      ::game::_Vec2_default_instance_);
}
inline const ::game::Vec2& EntityState::vel() const {
  // @@protoc_insertion_point(field_get:game.EntityState.vel)
  return _internal_vel();
}
inline void EntityState::unsafe_arena_set_allocated_vel(
    ::game::Vec2* vel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vel_);
  }
  vel_ = vel;
  if (vel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game.EntityState.vel)
}
inline ::game::Vec2* EntityState::release_vel() {
  
  ::game::Vec2* temp = vel_;
  vel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game::Vec2* EntityState::unsafe_arena_release_vel() {
  // @@protoc_insertion_point(field_release:game.EntityState.vel)
  
  ::game::Vec2* temp = vel_;
  vel_ = nullptr;
  return temp;
}
inline ::game::Vec2* EntityState::_internal_mutable_vel() {
  
  if (vel_ == nullptr) {
    auto* p = CreateMaybeMessage<::game::Vec2>(GetArenaForAllocation());
    vel_ = p;
  }
  return vel_;
}
inline ::game::Vec2* EntityState::mutable_vel() {
  ::game::Vec2* _msg = _internal_mutable_vel();
  // @@protoc_insertion_point(field_mutable:game.EntityState.vel)
  return _msg;
}
inline void EntityState::set_allocated_vel(::game::Vec2* vel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete vel_;
  }
  if (vel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(vel);
    if (message_arena != submessage_arena) {
      vel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vel, submessage_arena);
    }
    
  } else {
    
  }
  vel_ = vel;
  // @@protoc_insertion_point(field_set_allocated:game.EntityState.vel)
}

// int32 hp = 5;
inline void EntityState::clear_hp() {
  hp_ = 0;
}
inline int32_t EntityState::_internal_hp() const {
  return hp_;
}
inline int32_t EntityState::hp() const {
  // @@protoc_insertion_point(field_get:game.EntityState.hp)
  return _internal_hp();
}
inline void EntityState::_internal_set_hp(int32_t value) {
  
  hp_ = value;
}
inline void EntityState::set_hp(int32_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:game.EntityState.hp)
}

// uint32 anim = 6;
inline void EntityState::clear_anim() {
  anim_ = 0u;
}
inline uint32_t EntityState::_internal_anim() const {
  return anim_;
}
inline uint32_t EntityState::anim() const {
  // @@protoc_insertion_point(field_get:game.EntityState.anim)
  return _internal_anim();
}
inline void EntityState::_internal_set_anim(uint32_t value) {
  
  anim_ = value;
}
inline void EntityState::set_anim(uint32_t value) {
  _internal_set_anim(value);
  // @@protoc_insertion_point(field_set:game.EntityState.anim)
}

// uint64 owner = 7;
inline void EntityState::clear_owner() {
  owner_ = uint64_t{0u};
}
inline uint64_t EntityState::_internal_owner() const {
  return owner_;
}
inline uint64_t EntityState::owner() const {
  // @@protoc_insertion_point(field_get:game.EntityState.owner)
  return _internal_owner();
}
inline void EntityState::_internal_set_owner(uint64_t value) {
  
  owner_ = value;
}
inline void EntityState::set_owner(uint64_t value) {
  _internal_set_owner(value);
  // @@protoc_insertion_point(field_set:game.EntityState.owner)
}

// uint32 state = 8;
inline void EntityState::clear_state() {
  state_ = 0u;
}
inline uint32_t EntityState::_internal_state() const {
  return state_;
}
inline uint32_t EntityState::state() const {
  // @@protoc_insertion_point(field_get:game.EntityState.state)
  return _internal_state();
}
inline void EntityState::_internal_set_state(uint32_t value) {
  
  state_ = value;
}
inline void EntityState::set_state(uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:game.EntityState.state)
}

// -------------------------------------------------------------------

// ServerSnapshot

// uint32 server_tick = 1;
inline void ServerSnapshot::clear_server_tick() {
  server_tick_ = 0u;
}
inline uint32_t ServerSnapshot::_internal_server_tick() const {
  return server_tick_;
}
inline uint32_t ServerSnapshot::server_tick() const {
  // @@protoc_insertion_point(field_get:game.ServerSnapshot.server_tick)
  return _internal_server_tick();
}
inline void ServerSnapshot::_internal_set_server_tick(uint32_t value) {
  
  server_tick_ = value;
}
inline void ServerSnapshot::set_server_tick(uint32_t value) {
  _internal_set_server_tick(value);
  // @@protoc_insertion_point(field_set:game.ServerSnapshot.server_tick)
}

// uint32 snapshot_seq = 2;
inline void ServerSnapshot::clear_snapshot_seq() {
  snapshot_seq_ = 0u;
}
inline uint32_t ServerSnapshot::_internal_snapshot_seq() const {
  return snapshot_seq_;
}
inline uint32_t ServerSnapshot::snapshot_seq() const {
  // @@protoc_insertion_point(field_get:game.ServerSnapshot.snapshot_seq)
  return _internal_snapshot_seq();
}
inline void ServerSnapshot::_internal_set_snapshot_seq(uint32_t value) {
  
  snapshot_seq_ = value;
}
inline void ServerSnapshot::set_snapshot_seq(uint32_t value) {
  _internal_set_snapshot_seq(value);
  // @@protoc_insertion_point(field_set:game.ServerSnapshot.snapshot_seq)
}

// repeated .game.EntityState entities = 3;
inline int ServerSnapshot::_internal_entities_size() const {
  return entities_.size();
}
inline int ServerSnapshot::entities_size() const {
  return _internal_entities_size();
}
inline void ServerSnapshot::clear_entities() {
  entities_.Clear();
}
inline ::game::EntityState* ServerSnapshot::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:game.ServerSnapshot.entities)
  return entities_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::EntityState >*
ServerSnapshot::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:game.ServerSnapshot.entities)
  return &entities_;
}
inline const ::game::EntityState& ServerSnapshot::_internal_entities(int index) const {
  return entities_.Get(index);
}
inline const ::game::EntityState& ServerSnapshot::entities(int index) const {
  // @@protoc_insertion_point(field_get:game.ServerSnapshot.entities)
  return _internal_entities(index);
}
inline ::game::EntityState* ServerSnapshot::_internal_add_entities() {
  return entities_.Add();
}
inline ::game::EntityState* ServerSnapshot::add_entities() {
  ::game::EntityState* _add = _internal_add_entities();
  // @@protoc_insertion_point(field_add:game.ServerSnapshot.entities)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::EntityState >&
ServerSnapshot::entities() const {
  // @@protoc_insertion_point(field_list:game.ServerSnapshot.entities)
  return entities_;
}

// repeated uint64 removed_ids = 4;
inline int ServerSnapshot::_internal_removed_ids_size() const {
  return removed_ids_.size();
}
inline int ServerSnapshot::removed_ids_size() const {
  return _internal_removed_ids_size();
}
inline void ServerSnapshot::clear_removed_ids() {
  removed_ids_.Clear();
}
inline uint64_t ServerSnapshot::_internal_removed_ids(int index) const {
  return removed_ids_.Get(index);
}
inline uint64_t ServerSnapshot::removed_ids(int index) const {
  // @@protoc_insertion_point(field_get:game.ServerSnapshot.removed_ids)
  return _internal_removed_ids(index);
}
inline void ServerSnapshot::set_removed_ids(int index, uint64_t value) {
  removed_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:game.ServerSnapshot.removed_ids)
}
inline void ServerSnapshot::_internal_add_removed_ids(uint64_t value) {
  removed_ids_.Add(value);
}
inline void ServerSnapshot::add_removed_ids(uint64_t value) {
  _internal_add_removed_ids(value);
  // @@protoc_insertion_point(field_add:game.ServerSnapshot.removed_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
ServerSnapshot::_internal_removed_ids() const {
  return removed_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
ServerSnapshot::removed_ids() const {
  // @@protoc_insertion_point(field_list:game.ServerSnapshot.removed_ids)
  return _internal_removed_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
ServerSnapshot::_internal_mutable_removed_ids() {
  return &removed_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
ServerSnapshot::mutable_removed_ids() {
  // @@protoc_insertion_point(field_mutable_list:game.ServerSnapshot.removed_ids)
  return _internal_mutable_removed_ids();
}

// -------------------------------------------------------------------

// SpawnBullet

// uint32 id = 1;
inline void SpawnBullet::clear_id() {
  id_ = 0u;
}
inline uint32_t SpawnBullet::_internal_id() const {
  return id_;
}
inline uint32_t SpawnBullet::id() const {
  // @@protoc_insertion_point(field_get:game.SpawnBullet.id)
  return _internal_id();
}
inline void SpawnBullet::_internal_set_id(uint32_t value) {
  
  id_ = value;
}
inline void SpawnBullet::set_id(uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:game.SpawnBullet.id)
}

// uint32 owner = 2;
inline void SpawnBullet::clear_owner() {
  owner_ = 0u;
}
inline uint32_t SpawnBullet::_internal_owner() const {
  return owner_;
}
inline uint32_t SpawnBullet::owner() const {
  // @@protoc_insertion_point(field_get:game.SpawnBullet.owner)
  return _internal_owner();
}
inline void SpawnBullet::_internal_set_owner(uint32_t value) {
  
  owner_ = value;
}
inline void SpawnBullet::set_owner(uint32_t value) {
  _internal_set_owner(value);
  // @@protoc_insertion_point(field_set:game.SpawnBullet.owner)
}

// .game.Vec2 pos = 3;
inline bool SpawnBullet::_internal_has_pos() const {
  return this != internal_default_instance() && pos_ != nullptr;
}
inline bool SpawnBullet::has_pos() const {
  return _internal_has_pos();
}
inline void SpawnBullet::clear_pos() {
  if (GetArenaForAllocation() == nullptr && pos_ != nullptr) {
    delete pos_;
  }
  pos_ = nullptr;
}
inline const ::game::Vec2& SpawnBullet::_internal_pos() const {
  const ::game::Vec2* p = pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::game::Vec2&>(
      ::game::_Vec2_default_instance_);
}
inline const ::game::Vec2& SpawnBullet::pos() const {
  // @@protoc_insertion_point(field_get:game.SpawnBullet.pos)
  return _internal_pos();
}
inline void SpawnBullet::unsafe_arena_set_allocated_pos(
    ::game::Vec2* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pos_);
  }
  pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game.SpawnBullet.pos)
}
inline ::game::Vec2* SpawnBullet::release_pos() {
  
  ::game::Vec2* temp = pos_;
  pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game::Vec2* SpawnBullet::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:game.SpawnBullet.pos)
  
  ::game::Vec2* temp = pos_;
  pos_ = nullptr;
  return temp;
}
inline ::game::Vec2* SpawnBullet::_internal_mutable_pos() {
  
  if (pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::game::Vec2>(GetArenaForAllocation());
    pos_ = p;
  }
  return pos_;
}
inline ::game::Vec2* SpawnBullet::mutable_pos() {
  ::game::Vec2* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:game.SpawnBullet.pos)
  return _msg;
}
inline void SpawnBullet::set_allocated_pos(::game::Vec2* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete pos_;
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos);
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:game.SpawnBullet.pos)
}

// .game.Vec2 vel = 4;
inline bool SpawnBullet::_internal_has_vel() const {
  return this != internal_default_instance() && vel_ != nullptr;
}
inline bool SpawnBullet::has_vel() const {
  return _internal_has_vel();
}
inline void SpawnBullet::clear_vel() {
  if (GetArenaForAllocation() == nullptr && vel_ != nullptr) {
    delete vel_;
  }
  vel_ = nullptr;
}
inline const ::game::Vec2& SpawnBullet::_internal_vel() const {
  const ::game::Vec2* p = vel_;
  return p != nullptr ? *p : reinterpret_cast<const ::game::Vec2&>(
      ::game::_Vec2_default_instance_);
}
inline const ::game::Vec2& SpawnBullet::vel() const {
  // @@protoc_insertion_point(field_get:game.SpawnBullet.vel)
  return _internal_vel();
}
inline void SpawnBullet::unsafe_arena_set_allocated_vel(
    ::game::Vec2* vel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vel_);
  }
  vel_ = vel;
  if (vel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game.SpawnBullet.vel)
}
inline ::game::Vec2* SpawnBullet::release_vel() {
  
  ::game::Vec2* temp = vel_;
  vel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game::Vec2* SpawnBullet::unsafe_arena_release_vel() {
  // @@protoc_insertion_point(field_release:game.SpawnBullet.vel)
  
  ::game::Vec2* temp = vel_;
  vel_ = nullptr;
  return temp;
}
inline ::game::Vec2* SpawnBullet::_internal_mutable_vel() {
  
  if (vel_ == nullptr) {
    auto* p = CreateMaybeMessage<::game::Vec2>(GetArenaForAllocation());
    vel_ = p;
  }
  return vel_;
}
inline ::game::Vec2* SpawnBullet::mutable_vel() {
  ::game::Vec2* _msg = _internal_mutable_vel();
  // @@protoc_insertion_point(field_mutable:game.SpawnBullet.vel)
  return _msg;
}
inline void SpawnBullet::set_allocated_vel(::game::Vec2* vel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete vel_;
  }
  if (vel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(vel);
    if (message_arena != submessage_arena) {
      vel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vel, submessage_arena);
    }
    
  } else {
    
  }
  vel_ = vel;
  // @@protoc_insertion_point(field_set_allocated:game.SpawnBullet.vel)
}

// uint32 damage = 5;
inline void SpawnBullet::clear_damage() {
  damage_ = 0u;
}
inline uint32_t SpawnBullet::_internal_damage() const {
  return damage_;
}
inline uint32_t SpawnBullet::damage() const {
  // @@protoc_insertion_point(field_get:game.SpawnBullet.damage)
  return _internal_damage();
}
inline void SpawnBullet::_internal_set_damage(uint32_t value) {
  
  damage_ = value;
}
inline void SpawnBullet::set_damage(uint32_t value) {
  _internal_set_damage(value);
  // @@protoc_insertion_point(field_set:game.SpawnBullet.damage)
}

// uint32 ttl_ms = 6;
inline void SpawnBullet::clear_ttl_ms() {
  ttl_ms_ = 0u;
}
inline uint32_t SpawnBullet::_internal_ttl_ms() const {
  return ttl_ms_;
}
inline uint32_t SpawnBullet::ttl_ms() const {
  // @@protoc_insertion_point(field_get:game.SpawnBullet.ttl_ms)
  return _internal_ttl_ms();
}
inline void SpawnBullet::_internal_set_ttl_ms(uint32_t value) {
  
  ttl_ms_ = value;
}
inline void SpawnBullet::set_ttl_ms(uint32_t value) {
  _internal_set_ttl_ms(value);
  // @@protoc_insertion_point(field_set:game.SpawnBullet.ttl_ms)
}

// -------------------------------------------------------------------

// BulletBatch

// repeated .game.SpawnBullet spawns = 1;
inline int BulletBatch::_internal_spawns_size() const {
  return spawns_.size();
}
inline int BulletBatch::spawns_size() const {
  return _internal_spawns_size();
}
inline void BulletBatch::clear_spawns() {
  spawns_.Clear();
}
inline ::game::SpawnBullet* BulletBatch::mutable_spawns(int index) {
  // @@protoc_insertion_point(field_mutable:game.BulletBatch.spawns)
  return spawns_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::SpawnBullet >*
BulletBatch::mutable_spawns() {
  // @@protoc_insertion_point(field_mutable_list:game.BulletBatch.spawns)
  return &spawns_;
}
inline const ::game::SpawnBullet& BulletBatch::_internal_spawns(int index) const {
  return spawns_.Get(index);
}
inline const ::game::SpawnBullet& BulletBatch::spawns(int index) const {
  // @@protoc_insertion_point(field_get:game.BulletBatch.spawns)
  return _internal_spawns(index);
}
inline ::game::SpawnBullet* BulletBatch::_internal_add_spawns() {
  return spawns_.Add();
}
inline ::game::SpawnBullet* BulletBatch::add_spawns() {
  ::game::SpawnBullet* _add = _internal_add_spawns();
  // @@protoc_insertion_point(field_add:game.BulletBatch.spawns)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game::SpawnBullet >&
BulletBatch::spawns() const {
  // @@protoc_insertion_point(field_list:game.BulletBatch.spawns)
  return spawns_;
}

// repeated uint32 destroyed_ids = 2;
inline int BulletBatch::_internal_destroyed_ids_size() const {
  return destroyed_ids_.size();
}
inline int BulletBatch::destroyed_ids_size() const {
  return _internal_destroyed_ids_size();
}
inline void BulletBatch::clear_destroyed_ids() {
  destroyed_ids_.Clear();
}
inline uint32_t BulletBatch::_internal_destroyed_ids(int index) const {
  return destroyed_ids_.Get(index);
}
inline uint32_t BulletBatch::destroyed_ids(int index) const {
  // @@protoc_insertion_point(field_get:game.BulletBatch.destroyed_ids)
  return _internal_destroyed_ids(index);
}
inline void BulletBatch::set_destroyed_ids(int index, uint32_t value) {
  destroyed_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:game.BulletBatch.destroyed_ids)
}
inline void BulletBatch::_internal_add_destroyed_ids(uint32_t value) {
  destroyed_ids_.Add(value);
}
inline void BulletBatch::add_destroyed_ids(uint32_t value) {
  _internal_add_destroyed_ids(value);
  // @@protoc_insertion_point(field_add:game.BulletBatch.destroyed_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
BulletBatch::_internal_destroyed_ids() const {
  return destroyed_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
BulletBatch::destroyed_ids() const {
  // @@protoc_insertion_point(field_list:game.BulletBatch.destroyed_ids)
  return _internal_destroyed_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
BulletBatch::_internal_mutable_destroyed_ids() {
  return &destroyed_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
BulletBatch::mutable_destroyed_ids() {
  // @@protoc_insertion_point(field_mutable_list:game.BulletBatch.destroyed_ids)
  return _internal_mutable_destroyed_ids();
}

// uint32 server_tick = 3;
inline void BulletBatch::clear_server_tick() {
  server_tick_ = 0u;
}
inline uint32_t BulletBatch::_internal_server_tick() const {
  return server_tick_;
}
inline uint32_t BulletBatch::server_tick() const {
  // @@protoc_insertion_point(field_get:game.BulletBatch.server_tick)
  return _internal_server_tick();
}
inline void BulletBatch::_internal_set_server_tick(uint32_t value) {
  
  server_tick_ = value;
}
inline void BulletBatch::set_server_tick(uint32_t value) {
  _internal_set_server_tick(value);
  // @@protoc_insertion_point(field_set:game.BulletBatch.server_tick)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace game

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::game::EntityType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game::EntityType>() {
  return ::game::EntityType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_2eproto
